name: Terraform Docs

on:

  push:

jobs:

  docs:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: terraform-docs/gh-actions@v1

        with:

          working-dir: .

          output-file: README.md

          git-push: true
